import type {Metadata} from "next";
import {Inter, Vazirmatn} from "next/font/google";
import "./globals.css";

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-inter',
});

const vazirmatn = Vazirmatn({subsets: ['arabic'], variable: '--font-vazir'});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({children}: LayoutProps<"/">) {
	return (
			<html
					lang="en"
					className={`${vazirmatn.variable} ${inter.variable} h-full antialiased`}
			>
			<body className="min-h-full flex flex-col">{children}</body>
			</html>
	);
}
